### ISSUE TITLE
support tcpping delay test

### ISSUE THREAD

**Issue by airborne007** [RMTT/Shadowray#2]
Hello, I really like this project. She solves my big problem with v2ray subscriptions.
However, a subscription often contains many hosts, so it will be better to provide a feature to find out the faster host by tcpping delay testing. With this feature, users can select the best host to connect and this is really useful.
I hope to get your support.

**Comment by RMTT** [comment]
Hello,guy,thanks for your response. TCP delay testing is a good idea,but i have no time to do it now.But if I have enough time,i will do it,maybe after a week,because i am focusing on my final exam of this semester.
And,i really feel happy to see your response.

**Comment by RMTT** [comment]
And thanks for your pr.

**Comment by RMTT** [comment]
Already done.
